# documentation: https://wiki.archlinux.org/title/Alacritty
# config documentation: https://alacritty.org/config-alacritty.html

# themes:
# dracula: git clone https://github.com/dracula/alacritty to ~/.config/alacritty/themes/dracula
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]

[env]
TERM = "xterm-256color"

# `fc-list : family style |grep JetBranins` to get the font family and style
[font]
size = 18
offset = { x = 1, y = 0 }

[font.normal]
family = "JetBrains Mono NL"
style = "Light Italic"

[font.bold]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "ExtraBold Italic"

# margin left, right, top, bottom
[window.padding]
x = 16
y = 16

[window]
opacity = 1.0
# decorations = "None" # for no title bar: "Full" | "None" | "Transparent" | "Buttonless"
dimensions = { columns = 100, lines = 30 }
decorations_theme_variant = "Dark"         # "Dark" | "Light" | "None"

[keyboard]
bindings = [
	# remapping the keys `Command+K` to do nothing (to avoid clearing the screen)
	{ key = "K", mods = "Command", action = "None" },
]
