# config documentation: https://alacritty.org/config-alacritty.html

# themes:
# dracula: git clone https://github.com/dracula/alacritty to ~/.config/alacritty/themes/dracula
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]

[env]
TERM = "xterm-256color"

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new-session", "-A", "-s", "main"]

# `fc-list : family style |grep JetBranins` to get the font family and style
[font]
size = 16
offset = { x = 1, y = 0 }

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "ExtraBold Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Light Italic"

# [font.normal]
# family = "Hack Nerd Font"
# style = "Italic"


# [font.bold]
# family = "Hack Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "Hack Nerd Font"
# style = "Italic"
#
# [font.bold_italic]
# family = "Hack Nerd Font"
# style = "Bold Italic"


# [cursor]
# blink_interval = 500

# [cursor.style]
# shape = "Underline"
# blinking = "Always"

# margin left, right, top, bottom
[window.padding]
x = 16
y = 16

[window]
opacity = 1.0
# decorations = "None" # for no title bar: "Full" | "None" | "Transparent" | "Buttonless"
dimensions = { columns = 100, lines = 30 }
decorations_theme_variant = "Dark"         # "Dark" | "Light" | "None"

[keyboard]
bindings = [
	# remapping the keys `Command+K` to do nothing (to avoid clearing the screen)
	{ key = "K", mods = "Command", action = "None" },
    # remapping the keys `Control+Option+O` to execute the script `~/.config/fzf/config.sh`
    { key= "O", mods= "Control|Shift", chars= "\u007e\u002f\u002e\u0063\u006f\u006e\u0066\u0069\u0067\u002f\u0066\u007a\u0066\u002f\u006c\u0061\u0075\u006e\u0063\u0068\u0070\u0061\u0064\u002e\u0073\u0068\u000D" },
    # remapping the keys `Control+Option+P` to execute the script `~/.config/fzf/config.sh files`
    { key= "P", mods= "Control", chars= "\u007e\u002f\u002e\u0063\u006f\u006e\u0066\u0069\u0067\u002f\u0066\u007a\u0066\u002f\u006c\u0061\u0075\u006e\u0063\u0068\u0070\u0061\u0064\u002e\u0073\u0068\u0020\u0066\u0069\u006c\u0065\u0073\u000D" },
    # remapping the keys `Control+Option+P` to execute the script `~/.config/fzf/config.sh folders`
    { key= "P", mods= "Control|Shift", chars= "\u007e\u002f\u002e\u0063\u006f\u006e\u0066\u0069\u0067\u002f\u0066\u007a\u0066\u002f\u006c\u0061\u0075\u006e\u0063\u0068\u0070\u0061\u0064\u002e\u0073\u0068\u0020\u0066\u006f\u006c\u0064\u0065\u0072\u0073\u000D" },
]

