# documentation: https://wiki.archlinux.org/title/Alacritty

# themes:
# dracula: git clone https://github.com/dracula/alacritty to ~/.config/alacritty/themes/dracula
import = ["~/.config/alacritty/themes/dracula/dracula.toml"]

[env]
TERM = "xterm-256color"

# `fc-list : family style |grep JetBranins` to get the font family and style
[font]
size = 18

[font.normal]
family = "JetBrains Mono NL"
style = "Light Italic"

[font.bold]
family = "JetBrains Mono NL"
style = "ExtraBold Italic,Italic"

[font.bold_italic]
family = "JetBrains Mono NL"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono NL"
style = "ExtraBold Italic"
